spring:
  application:
    name: nasa_apod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: apod_schema

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

api:
  nasa:
    key: ${NASA_API_KEY}
    base-url: https://api.nasa.gov

  deepl:
    key: ${DEEPL_API_KEY}
